# Generated by Django 3.2 on 2024-06-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='followers_count',
            field=models.IntegerField(default=0),
        ),
    ]
