# Generated by Django 3.2 on 2024-06-08 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(
                upload_to='images/', default='../default_profile_1_yiwhh2'
            ),
        ),
    ]
