# Generated by Django 3.2 on 2024-06-08 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='followers_count',
            field=models.IntegerField(default=0),
        ),
    ]
