# Generated by Django 3.2.25 on 2024-05-21 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='channel_filter',
            field=models.CharField(choices=[('_1977', '1977'), ('brannan', 'Brannan')], default='nomral', max_length=32),
        ),
    ]
