# Generated by Django 3.2.25 on 2024-05-21 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0002_channel_channel_filter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='channel_filter',
            field=models.CharField(choices=[('warhammer', 'WarHammer'), ('films', 'Films')], default='nomral', max_length=32),
        ),
    ]
