# Generated by Django 3.2.25 on 2024-05-21 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0003_alter_channel_channel_filter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='channel_filter',
        ),
    ]
