# Generated by Django 3.2.25 on 2024-05-21 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0004_remove_channel_channel_filter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel',
            old_name='created_by',
            new_name='owner',
        ),
    ]
