# Generated by Django 3.2.25 on 2024-05-21 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0005_rename_created_by_channel_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel',
            old_name='name',
            new_name='title',
        ),
    ]
